services:
  mongodb:
    image: mongo:7.0-jammy
    container_name: mongodb
    ports:
      - "27007:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - backend
    restart: always

networks:
  backend:

volumes:
  mongodb-data:
